---
- name: Check OS version
  hosts: all
  gather_facts: true  # Bật tính năng thu thập thông tin
  tasks:
    - name: Display OS version
      debug:
        msg: "The operating system is {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Check CUPS service status
      ansible.builtin.systemd:
        name: cups
        state: started
      register: cups_status
    - name: Show CUPS service status
      debug:
        var: cups_status