---
- name: Check OS version
  hosts: all
  gather_facts: true  # Bật tính năng thu thập thông tin
  tasks:
    - name: Check Pgpool2 service status
      ansible.builtin.systemd:
        name: pgpool2
        state: started
      register: pgpool2_status
      ignore_errors: yes
    - name: Skip task if Pgpool2 service does not exist
      meta: end_host
      when: "'Could not find the requested service' in pgpool2_status.msg"
    - name: Show Pgpool service status
      debug:
        var: pgpool2_status