---
- name: Open a port on pfSense
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Get current user
      command: whoami
      register: current_user  # Lưu kết quả vào biến

    - name: Show current user
      debug:
        msg: "Current user is: {{ current_user.stdout }}"

    - name: List /root directory to verify sudo access
      command: ls /root
      register: root_list
      ignore_errors: true  # Để tránh thất bại nếu không có quyền

    - name: Show root list
      debug:
        msg: "Current user is: {{ root_list.stdout }}"

    - name: "Add Internal DNS out rule"
      pfsensible.core.pfsense_rule:
        name: 'Allow Internal DNS traffic out'
        action: pass
        interface: lan
        ipprotocol: inet
        protocol: udp
        source: any
        destination: any
        destination_port: 53
        state: present