---
- name: Open a port on pfSense
  hosts: all
  gather_facts: true
  tasks:
    - name: "Add Internal DNS out rule"
      pfsense.core.pfsense_rule:
        name: 'Allow Internal DNS traffic out'
        action: pass
        interface: lan
        ipprotocol: inet
        protocol: udp
        source: dns_int
        destination: any
        destination_port: 53
        after: 'Allow proxies out'
        state: present